### ISSUE TITLE
[Bug/request?] change the sorting algoritm

### ISSUE THREAD

**Issue by Bart274** [coryo/ComicReader.bundle#4]
Hi,

Is the sorting algoritm defined by your channel or by Plex?
If you define it, could you try to finetune the sorting by reading the integers in the filename as a complete number? For example: when you use a hashtag in a filename on Windows the complete number will be read and used for sorting, so you can name your comics `#1` instead of `#001` to get the right sorting.
Now in the channel my comics go like: 228, 229, 23, 230, 231,...

**Comment by coryo** [comment]
I did a quick implementation of this in version 1.2.0, check the releases tab. 

I don't have many comics to test with so let me know if there are problems.

**Comment by Bart274** [comment]
Thanks a lot! I'll test it tomorrow! :)
I have about 43k comics in one huge directory now :p

**Comment by Bart274** [comment]
The paging works :)

**Comment by Bart274** [comment]
As you can see, the sorting is still off:

**Comment by coryo** [comment]
I fixed sorting on the comic pages, but not the directory listing. I should have it fixed now.

the channel self updater has a 12 hour cache, so you will probably have to manually install if you want to test it.

**Comment by Bart274** [comment]
the sorting works perfectly now! thanks a lot! :)
