### ISSUE TITLE
Error: Unknown command "p"

### ISSUE THREAD

**Issue by dfurball** [coryo/ComicReader.bundle#7]
Files: CBR
Error: Unknown command "p"
Unrar Path: C:\Program Files\WinRAR\WinRAR.exe
7-Zip Path: C:\Program Files\7-Zip\7zFM.exe

![unknown command](https://cloud.githubusercontent.com/assets/8889662/20077137/bdda7604-a500-11e6-86a2-e37c306ca2dc.jpg)

**Comment by coryo** [comment]
the exe paths should be:
Unrar Path: C:\Program Files\WinRAR\\**unrar.exe**
7-Zip Path: C:\Program Files\7-Zip\\**7z.exe**

**Comment by dfurball** [comment]
Ahh silly me. 
Thanks for the speedy reply.
Works like a charm now.
